version: '3.9'

services:
  db:
    image: postgres:16.4
    container_name: nordicictbackend-db
    environment:
      POSTGRES_DB: nordic_ict_db
      POSTGRES_USER: bojucode
      POSTGRES_PASSWORD: bojucode
    ports:
      - "5331:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nordicictbackend-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nordic_ict_db
      SPRING_DATASOURCE_USERNAME: bojucode
      SPRING_DATASOURCE_PASSWORD: bojucode
    ports:
      - "8080:8080"

volumes:
  db_data:
