version: "3.9"

services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: bojucode
      POSTGRES_PASSWORD: bojucode
      POSTGRES_DB: nordic_ict_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5331:5432"
    networks:
      - backend-net
    restart: unless-stopped

  app:
    image: nordicictbackend:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nordic_ict_db
      SPRING_DATASOURCE_USERNAME: bojucode
      SPRING_DATASOURCE_PASSWORD: bojucode
    ports:
      - "9090:8080"
    networks:
      - backend-net
    restart: unless-stopped

networks:
  backend-net:
    driver: bridge

volumes:
  db-data:
