spring.application.name=NordicICTBackend

# Database
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d3n4ohj3fgac73aba43g-a.oregon-postgres.render.com:5432/nordic_ict_db
#jdbc:postgresql://localhost:5331/nordic_ict_db
spring.datasource.username=bojucode
#bojucode
spring.datasource.password=0RG17iuZZtWgIf9qf80TBHbKa1d4AHn9
#bojucode

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.user=bojucode
#bojucode
spring.flyway.password=0RG17iuZZtWgIf9qf80TBHbKa1d4AHn9
#bojucode
spring.flyway.baseline-description=Initial migration
spring.flyway.baseline-version=0

# Maximum file size
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# Supabase
supabase.url=https://rjiozcbtszmyehzffzpa.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqaW96Y2J0c3pteWVoemZmenBhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDg0MDI4MywiZXhwIjoyMDY2NDE2MjgzfQ.DognSJ1haPueVWjwL60NoGW4cboCktmu8DEWrPHC-jA

supabase.filepath=AdminPhotos/
supabase.basefilepath=/storage/v1/object/
supabase.admin.bucket=AdminPhotos

jwt.secret=qJKLOweFDVSGrtyuiopasdfghjklzHBSGFBGFSxcvbnm1234567VDJYJ89qwertyuiASGFRSHTVADFVxcvbnsdfghjDVDFBVdgsflgjhslfDFAGFFjghbsjgNGJYUKJNGDFB564T80VJU5489YU9O547BYTNVWYH7VY4NQCUNJNnsolfbnsVCDAdkgfnbSDFHGTREJHTNBHGFsgfmvnbdlfgbndfkgjn
jwt.accessexpiration=60000000

jwt.refreshexpiration=2000000000



# GitHub OAuth2 registration
spring.security.oauth2.client.registration.github.client-id=Ov23lijIRUlolwMQmCBb
spring.security.oauth2.client.registration.github.client-secret=efbcfca0b6723caff561ef152cd6bacbd0b4eca3
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github
spring.security.oauth2.client.registration.github.scope=read:user


spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=login

# Optional: just for clarity
spring.security.oauth2.client.registration.github.client-name=GitHub


logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG

