CREATE TABLE admin_model
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname  VARCHAR(255)                            NOT NULL,
    lastname   VARCHAR(255)                            NOT NULL,
    middlename VARCHAR(255),
    password   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_adminmodel PRIMARY KEY (id)
);

CREATE TABLE news_model
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(255)                            NOT NULL,
    content   VARCHAR(255)                            NOT NULL,
    thumbnail VARCHAR(255)                            NOT NULL,
    createdat VARCHAR(255)                            NOT NULL,
    link      VARCHAR(255),
    CONSTRAINT pk_newsmodel PRIMARY KEY (id)
);

CREATE TABLE partner_model
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    logourl VARCHAR(255)                            NOT NULL,
    weblink VARCHAR(255),
    CONSTRAINT pk_partnermodel PRIMARY KEY (id)
);

CREATE TABLE project_model
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    logourl     VARCHAR(255)                            NOT NULL,
    weblink     VARCHAR(255),
    startdate   TIMESTAMP                               NOT NULL,
    enddate     TIMESTAMP,
    status      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_projectmodel PRIMARY KEY (id)
);

CREATE TABLE subscriber_model
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname  VARCHAR(255)                            NOT NULL,
    lastname   VARCHAR(255)                            NOT NULL,
    middlename VARCHAR(255),
    email      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_subscribermodel PRIMARY KEY (id)
);

