ALTER TABLE partner_model
ADD COLUMN industry VARCHAR(255),
ADD COLUMN location VARCHAR(255),
ADD COLUMN description VARCHAR(255),
ADD COLUMN status VARCHAR(255),
ADD COLUMN email VARCHAR(255),
ADD COLUMN phonenumber VARCHAR(255),
ADD COLUMN phone VARCHAR(255),
ADD COLUMN type VARCHAR(255);