CREATE TABLE jwt_model
(
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  token     VARCHAR(255)                            NOT NULL,
  issuedat  TIMESTAMP                               NOT NULL,
  expiresat TIMESTAMP                               NOT NULL,
  useremail VARCHAR(255)                            NOT NULL,
  CONSTRAINT pk_jwtmodel PRIMARY KEY (id)
)